
services:
  flask-backend:
    container_name: flask-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    networks:
      - app-network

  expo-frontend:
    container_name: expo-frontend
    build:
      context: ./chat-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./chat-app:/app
    networks:
      - app-network
    depends_on:
      - flask-backend

networks:
  app-network:
    driver: bridge