name: libbit_chat_app

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  
  # Packeges for styling
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Utility packages
  encrypt: ^5.0.3
  http: ^1.3.0
  pointycastle: ^3.6.2
  socket_io_client: ^3.0.2
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  provider: ^6.1.4
  flutter_webrtc: ^0.13.1+hotfix.1
  intl: ^0.20.2
  http_parser: ^4.1.2
  path: ^1.9.1
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logos/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # fonts:
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-ExtraBold.ttf
    #       weight: 800

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700